name: PR Request

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Pull latest code
        run: /var/www/html/deployment/deployment-test-cd.sh